<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="DESKTOP-3S3P68U" name="com.learnautomation.testcases.LoginTestWithPOMWithFactory" tests="4" failures="0" timestamp="2022-01-23T10:45:50 IST" time="0.056" errors="1">
  <testcase name="login" time="0.000" classname="com.learnautomation.testcases.LoginTestWithPOMWithFactory">
    <skipped/>
  </testcase> <!-- login -->
  <system-out/>
  <testcase name="setup" time="0.056" classname="com.learnautomation.testcases.LoginTestWithPOMWithFactory">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.learnautomation.factory.BrowserFactory.startBrowser(BrowserFactory.java:27)
at com.learnautomation.base.BaseClass.setup(BaseClass.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- setup -->
  <system-out/>
  <testcase name="verifyTabs" time="0.000" classname="com.learnautomation.testcases.LoginTestWithPOMWithFactory">
    <skipped/>
  </testcase> <!-- verifyTabs -->
  <system-out/>
  <testcase name="logOutApplication" time="0.000" classname="com.learnautomation.testcases.LoginTestWithPOMWithFactory">
    <skipped/>
  </testcase> <!-- logOutApplication -->
  <system-out/>
</testsuite> <!-- com.learnautomation.testcases.LoginTestWithPOMWithFactory -->
